# theme used
remote_theme: pmarsceill/just-the-docs

title: RAPIDS Standards
description: Documentation of processes and standards followed by RAPIDS
baseurl: "/standards/" # the subpath of your site, e.g. /blog

permalink: pretty
exclude: ["README.md"]

aux_links:
    "View RAPIDS on GitHub":
      - "https://github.com/rapidsai"

# Enable or disable the site search
search_enabled: true
